### PR TITLE
Changed folder's name for dockerfile

### PR DESCRIPTION
**Pull request by jhonatantm9**

### CODE REVIEW

**Comment by jhonatantm9** [comment]
REview the code, thx

**Review by CamiloVelezP — COMMENTED** [review]
Change data to "Data"

**Review by sebasarias17 — COMMENTED** [review]
Put all the 'D' in uppercase

**Review by sebasarias17 — COMMENTED** [review]
Good Job Buddy :p

**Review by CamiloVelezP — APPROVED** [review]
Nice Fix

**Review by sebasarias17 — APPROVED** [review]
Good Job :p

**Pull request merged**
